default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { 5432 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>

development:
  <<: *default
  database: hrms_development

test:
  <<: *default
  database: hrms_test

production:
  <<: *default
  database: hrms_production
  username: <%= ENV["HRMS_DATABASE_USER"] %>
  password: <%= ENV["HRMS_DATABASE_PASSWORD"] %>
